version: '3'
services:
  make:
    image: "paperist/alpine-texlive-ja"
    volumes:
      - ./:/workdir/
      - ./sty/:/usr/local/texlive/texmf-local/tex/

    command:
      sh generate.sh

  lint:
    build:
      context: .
      dockerfile: ./lint/Dockerfile
    volumes:
      - ./src/:/work/
      - ./lint/.textlintrc:/.textlintrc
      - ./lint/commands.sh:/commands.sh
      - ./lint/prh-rules.yml:/node_modules/textlint-rule-preset-ja-engineering-paper/src/dict/prh-rules.yml
      
    command:
      sh /commands.sh
